---
- hosts: all
  become: yes
  tasks:
    - name: Install package GIT
      package:
        name: git
        state: latest
        
    - name : 1. Install dépendence pour GO
      shell : dnf groupinstall -y "Development Tools"
    - name : 2. Install dépendence pour GO
      shell : dnf groupinstall -y "Development Tools"
