---
- hosts: all
  become: yes
  tasks:
    - name: Install package GIT
      package:
        name: git
        state: latest
    - name: Install DEP for GO
      shell: dnf groupinstall -y "Development Tools"
    - name: Install GO
      shell: dnf install -y go golang
    - name: Start Go project
      shell: |
        git clone https://github.com/BastienBalaud/golang-myip.git
        cd golang-myip/
        make
        cp build/server.x86_64 /usr/bin/
    - name: Create golang-myip service P1
      file:
        path: "/etc/systemd/system/golanip.service"
        state: touch
    - name: Create golang-myip service P2
      copy:
        dest: "/etc/systemd/system/golanip.service"
        content: |
          [Unit]
          Description=Golang-myIP
          [Service]
          Type=simple
          ExecStart=/root/golang-myip/build/server.x86_64 --port 80
          Restart=always
          [Install]
          WantedBy=multi-user.target
    - name: Desable SELinux
      shell: setenforce 0
    - name: Enable golang-myip
      shell: |
        cp ../golangip.service /etc/systemd/system/
        systemctl enable golangip
        systemctl start golangip
    - name: Add SSH key
      shell: |
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILjIRqNf3oVs8vbAcoNHzXMxlS5fL6qqFxfdi221S9p6" >> /root/.ssh/authorized_keys
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAmM7WeoXFKZGnDLV8RA3jfeYKPIYzTNIe3Yqr7Z11BV" >> /root/.ssh/authorized_keys
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXNu2wW1ssMqlzRd3q/YodypM77UNFz7tF6h2v+hYYZ" >> /root/.ssh/authorized_keys
