---
- hosts: all
  become: yes
  tasks:
    - name: 1. Install package GIT
      package:
        name: git
        state: latest
    - name: 2. Install MAKE & GO
      shell: |
        dnf install -y make
        dnf install -y go golang
    - name: 3. Pull Golang-myip Project
      shell: |
        cd /tmp
        git clone https://github.com/BastienBalaud/golang-myip.git
    - name: 4. Compilate golang-myip
      make:
        chdir: /tmp/golang-myip/
    - name: 5. Copy Build into /usr/bin
      shell: cp /tmp/golang-myip/build/server.x86_64 /usr/bin
    - name: 6. Create golang-myip service P1
      file:
        path: "/etc/systemd/system/golanip.service"
        state: touch
    - name: 7. Create golang-myip service P2
      copy:
        dest: "/etc/systemd/system/golanip.service"
        content: |
          [Unit]
          Description=Golang-myIP
          [Service]
          Type=simple
          ExecStart=/usr/bin/server.x86_64 --port 80
          Restart=always
          [Install]
          WantedBy=multi-user.target
    - name: 8. Apply new SELinux file context to filesystem
      ansible.builtin.command: restorecon -irv /tmp/golang-myip/build/server.x86_64
    - name: 9. Enable golang-myip
      shell: |
        systemctl enable golangip
        systemctl start golangip
        systemctl daemon-reload
    - name: 10. Add SSH key
      shell: |
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILjIRqNf3oVs8vbAcoNHzXMxlS5fL6qqFxfdi221S9p6" >> /root/.ssh/authorized_keys
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAmM7WeoXFKZGnDLV8RA3jfeYKPIYzTNIe3Yqr7Z11BV" >> /root/.ssh/authorized_keys
       echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXNu2wW1ssMqlzRd3q/YodypM77UNFz7tF6h2v+hYYZ" >> /root/.ssh/authorized_keys
